version: '2.1'

services:

  app:
    image: ${IMAGE}:${IMAGE_VER}
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.${APP_TAG}.rule=Host(`${APP_SITE:?Must be set}`)
      - traefik.http.routers.${APP_TAG}.tls=${USE_TLS}
      - traefik.http.routers.${APP_TAG}.tls.certresolver=letsEncrypt
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - lan
#    command:
#      --debug
    environment:
      - TOKEN
    build:
      context: .

networks:
  lan:
    external:
      name: ${DCAPE_NET}
